version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./server/
    ports:
      - "3005:3005"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb